name: 'Plugin Machine'
description: 'Build, Zip and Upload Plugin'
inputs:
  token:  # id of input
    description: 'Plugin Machine Token'
    required: true
  path:
    description: Root directory of plugin
    required: true
outputs:
  url: # id of output
    description: 'URL of uploaded plugin'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.path }}

branding:
  icon: 'triangle'
  color: 'blue'
