name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:  # id of input
    description: 'Who to greet'
    required: true
  path:
    description: Root directory of plugin
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.path }}
